from __future__ import annotations
import html
from typing import Any
PHASE="Phase 32 - UI Polish Demo Navigation Pass"
GROUPS=[("Start Here",[("Command Center","/command-center"),("Demo Flow","/demo-flow"),("Demo Navigation","/demo-navigation"),("Demo Console","/demo-console")]),("Evidence Core",[("Scenario Library","/scenario-library-v4"),("Evaluation Matrix","/evaluation-matrix-v2"),("Expanded Benchmark","/expanded-benchmark"),("Evidence Export","/evidence-export")]),("Safety and Review",[("Reviewer Workspace","/reviewer-workspace"),("Decision Simulator","/decision-simulator"),("Audit Ledger","/audit-ledger"),("Review Workbench","/review-workbench")]),("AI and Explanation",[("Fireworks Advisory","/fireworks-advisory"),("Fireworks Coverage","/fireworks-coverage"),("LLM Advisory Eval","/llm-advisory-eval"),("Fireworks Model Card","/fireworks-model-card")]),("Integration and Partner Readiness",[("Integration Sandbox","/integration-sandbox"),("Integration Readiness","/integration-readiness"),("Partner API Contract","/partner-api-contract"),("Policy Sandbox","/policy-sandbox")]),("Readiness and Limits",[("Ops Readiness","/ops-readiness"),("Route Reliability","/route-reliability"),("Demo Safe Mode","/demo-safe-mode"),("Final Validation","/final-validation"),("Demo Freeze","/demo-freeze"),("Production Gap Analysis","/production-gap-analysis")])]
def get_demo_navigation_payload()->dict[str,Any]:
 groups=[]
 for group,items in GROUPS: groups.append({"group":group,"items":[{"title":title,"route":route,"purpose":f"Open the {title.lower()} evidence surface.","demoUse":"guided demo navigation","safetyBadge":"synthetic advisory","priority":"primary" if group=="Start Here" else "supporting"} for title,route in items]})
 return {"phase":PHASE,"status":"READY","syntheticOnly":True,"advisoryOnly":True,"runtimeGpuRequired":False,"runtimeExternalServiceRequired":False,"deterministicRulesAuthoritative":True,"autonomousActionsAllowed":False,"databaseRequired":False,"persistenceEnabled":False,"polishOnly":True,"architectureChanged":False,"dependenciesAdded":False,"navigationGroups":groups,"polishGuidelines":["consistent safety badges","back-to-command-center link","demo-flow link","mobile-friendly cards","no external CSS or JS","no architecture change"],"routeMap":{"demoNavigation":"/demo-navigation","navigationMap":"/navigation-map","demoFlow":"/demo-flow","demoFreeze":"/demo-freeze","commandCenter":"/command-center"}}
def get_navigation_map_payload()->dict[str,Any]: return get_demo_navigation_payload()
def render_demo_navigation_html()->str:
 p=get_demo_navigation_payload(); sections=""
 for group in p["navigationGroups"]: sections+=f'<section><h2>{html.escape(group["group"])}</h2><div class="grid">'+"".join(f'<article><span>{html.escape(x["safetyBadge"])}</span><h3>{html.escape(x["title"])}</h3><p>{html.escape(x["purpose"])}</p><a href="{html.escape(x["route"])}">Open</a></article>' for x in group["items"])+"</div></section>"
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demo Navigation</title><style>body{{font:16px system-ui;background:#07131b;color:#eef;padding:24px}}.hero,article{{background:#102631;padding:16px;border-radius:14px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}}a{{display:inline-block;border:1px solid #486;padding:8px;border-radius:9px;color:#9ed}}span{{color:#9ed}}</style></head><body><div class="hero"><h1>Demo Navigation</h1><p>Synthetic-only advisory navigation polish; deterministic rules remain authoritative.</p><a href="/demo-flow">Start demo</a> <a href="/demo-freeze">Freeze gate</a> <a href="/command-center">Command center</a></div>{sections}</body></html>'''
