from __future__ import annotations
import html
from typing import Any
PHASE="Phase 30 - Final Demo Flow Builder"
STEP_DATA=[("Command Center","/command-center"),("Scenario Library","/scenario-library-v4"),("Expanded Benchmark","/expanded-benchmark"),("Evaluation Matrix","/evaluation-matrix-v2"),("Raw Sensor / Data Contract","/raw-schema"),("Data Quality","/data-quality"),("Consensus","/consensus"),("SERS Advisory Risk","/sers"),("Reviewer Workspace","/reviewer-workspace"),("Audit Ledger","/audit-ledger"),("Fireworks Advisory / LLM Safety","/llm-advisory-eval"),("Partner API Contract","/partner-api-contract"),("Ops Readiness / Safe Mode","/route-reliability"),("Final Validation / Gap Analysis","/production-gap-analysis")]
def _step(number:int,title:str,route:str)->dict[str,Any]:
 return {"stepNumber":number,"title":title,"route":route,"purpose":f"Guide the audience through {title.lower()}.","presenterScript":f"Open {title} and explain the synthetic evidence boundary.","whatToShow":["primary evidence surface","deterministic boundary","human review handoff"],"safetyBoundary":"Synthetic advisory demo guidance only; no operational action.","expectedAudienceTakeaway":"The surface supports transparent synthetic evidence review.","nextStepRoute":f"/demo-flow/step-{number+1}" if number<14 else "/demo-flow"}
def get_demo_flow_payload()->dict[str,Any]:
 steps=[_step(i,*x) for i,x in enumerate(STEP_DATA,1)]
 return {"phase":PHASE,"status":"READY","syntheticOnly":True,"advisoryOnly":True,"runtimeGpuRequired":False,"runtimeExternalServiceRequired":False,"deterministicRulesAuthoritative":True,"autonomousActionsAllowed":False,"databaseRequired":False,"persistenceEnabled":False,"demoFreezeActive":False,"demoReadyButNotFrozen":True,"stepCount":14,"demoSteps":steps,"routeMap":{"demoFlow":"/demo-flow",**{f"step{i}":f"/demo-flow/step-{i}" for i in range(1,15)},"demoConsole":"/demo-console","judgeEvidence":"/judge-evidence","finalValidation":"/final-validation","productionGapAnalysis":"/production-gap-analysis"},"flowBoundaries":["demo guidance only","no production validation","no compliance certification","no autonomous operations","no real data","Jupyter/GPU used offline only","Fireworks optional"]}
def get_demo_step_payload(number:int)->dict[str,Any]:
 if not 1<=number<=14: raise KeyError(number)
 return get_demo_flow_payload()["demoSteps"][number-1]
def _badges()->str:return '<div class="badges"><span>Synthetic-only</span><span>Advisory-only</span><span>Demo not frozen</span><span>Deterministic rules authoritative</span><span>Runtime GPU required: false</span><span>Runtime external service required: false</span></div>'
STYLE='''<style>body{font:16px system-ui;background:#07131b;color:#eef;padding:24px}.hero,.card{background:#102631;padding:18px;border-radius:14px;margin:12px 0}.badges{display:flex;flex-wrap:wrap;gap:8px}.badges span,a{border:1px solid #486;padding:7px;border-radius:9px;color:#9ed}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}</style>'''
def render_demo_flow_html()->str:
 p=get_demo_flow_payload(); cards="".join(f'<article class="card"><h2>{s["stepNumber"]}. {html.escape(s["title"])}</h2><p>{html.escape(s["purpose"])}</p><a href="/demo-flow/step-{s["stepNumber"]}">Open step</a></article>' for s in p["demoSteps"]); boundaries="".join(f'<li>{html.escape(x)}</li>' for x in p["flowBoundaries"])
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Demo Flow</title>{STYLE}</head><body><div class="hero"><h1>Final Demo Flow Builder</h1><p>Start demo: guided synthetic advisory evidence; the demo is ready but not frozen.</p>{_badges()}<ul>{boundaries}</ul></div><section>{cards}</section></body></html>'
def render_demo_step_html(number:int)->str:
 s=get_demo_step_payload(number); prev=f'/demo-flow/step-{number-1}' if number>1 else '/demo-flow'; nxt=s["nextStepRoute"]
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(s["title"])}</title>{STYLE}</head><body><h1>Step {number}: {html.escape(s["title"])}</h1>{_badges()}<div class="card"><h2>Presenter script</h2><p>{html.escape(s["presenterScript"])}</p><p>{html.escape(s["safetyBoundary"])}</p><a href="{html.escape(s["route"])}">Open app route</a></div><p><a href="{prev}">Previous</a> <a href="{nxt}">Next</a></p></body></html>'
