from __future__ import annotations
import html, json
from typing import Any
from integration_readiness_v2 import PHASE2_FIELDS
PHASE="Phase 29 - Partner API Contract v2"

def get_partner_sample_request_payload()->dict[str,Any]:
 values={"timestampUtc":"2026-01-15T10:00:00Z","sensorId":"SYN-SENSOR-01","deviceId":"SYN-DEVICE-01","shipmentId":"SYN-SHIPMENT-01","containerId":"SYN-CONTAINER-01","zoneId":"SYN-ZONE-A","palletId":"SYN-PALLET-01","temperatureC":4.2,"humidityPercent":55.0,"batteryPercent":91,"signalStrength":-62,"doorOpen":False,"shockVibrationFlag":False,"tiltFlag":False,"lightExposureFlag":False,"locationProxy":"synthetic-location","readingSequence":1,"firmwareVersion":"demo-1.0","calibrationProfileId":"SYN-CAL-01","gatewayId":"SYN-GATEWAY-01","ingestionDelaySeconds":2}
 return {key:values[key] for key in PHASE2_FIELDS}

def get_partner_sample_response_payload()->dict[str,Any]:
 return {"requestId":"SYN-REQUEST-001","syntheticOnly":True,"advisoryOnly":True,"deterministicRulesAuthoritative":True,"autonomousActionsAllowed":False,"dataQualitySummary":{"status":"synthetic evidence accepted"},"consensusSummary":{"status":"synthetic agreement evaluated"},"sersAdvisory":{"riskBand":"WATCH","advisoryOnly":True},"humanReviewRequired":True,"blockedActions":["release","quarantine","discard","reroute","customer messaging"],"evidenceRoutes":["/data-quality","/consensus","/sers","/reviewer-workspace"]}

ERRORS=[{"code":code,"status":400 if code!="external_service_unavailable" else 503,"meaning":meaning} for code,meaning in (("malformed_payload","Payload shape is invalid."),("missing_required_field","A required synthetic field is absent."),("unsupported_case","Synthetic case is not in the catalog."),("unsafe_action_requested","Operational action requests are rejected."),("external_service_unavailable","Optional explanation service is unavailable; fallback remains available."),("evidence_incomplete","Human review requires more evidence."))]
def get_partner_error_catalog_payload()->dict[str,Any]: return {"syntheticOnly":True,"errorCatalog":ERRORS}

def get_openapi_preview_payload()->dict[str,Any]:
 reading={"type":"object","required":list(PHASE2_FIELDS),"properties":{f:{"type":"number" if f in ("temperatureC","humidityPercent","batteryPercent","signalStrength","ingestionDelaySeconds") else "boolean" if f in ("doorOpen","shockVibrationFlag","tiltFlag","lightExposureFlag") else "integer" if f=="readingSequence" else "string"} for f in PHASE2_FIELDS}}
 response_properties={f:{"type":"boolean" if isinstance(v,bool) else "array" if isinstance(v,list) else "object" if isinstance(v,dict) else "string"} for f,v in get_partner_sample_response_payload().items()}
 return {"openapi":"3.1.0","info":{"title":"ColdChain Sentinel Static Partner Contract Preview","version":"2.0.0","description":"Static preview only; not a live partner API."},"paths":{"/synthetic/advisory":{"post":{"summary":"Preview a synthetic sensor-window advisory request","requestBody":{"required":True,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/SyntheticSensorReading"}}}},"responses":{"200":{"description":"Advisory response","content":{"application/json":{"schema":{"$ref":"#/components/schemas/AdvisoryResponse"}}}},"400":{"description":"Error response","content":{"application/json":{"schema":{"$ref":"#/components/schemas/ErrorResponse"}}}}}}}},"components":{"schemas":{"SyntheticSensorReading":reading,"AdvisoryResponse":{"type":"object","required":list(response_properties),"properties":response_properties},"ErrorResponse":{"type":"object","required":["code","meaning"],"properties":{"code":{"type":"string"},"meaning":{"type":"string"}}}}},"staticPreviewOnly":True}

def get_partner_api_contract_payload()->dict[str,Any]:
 return {"phase":PHASE,"status":"READY","syntheticOnly":True,"advisoryOnly":True,"runtimeGpuRequired":False,"runtimeExternalServiceRequired":False,"deterministicRulesAuthoritative":True,"autonomousActionsAllowed":False,"externalCallsMade":False,"webhooksEnabled":False,"secretsRequired":False,"realPartnerIntegrationEnabled":False,"databaseRequired":False,"persistenceEnabled":False,"contractMode":"static-demo-contract","inboundContract":{"endpoint":"/partner-api-contract/sample-request.json","method":"POST","description":"synthetic sensor-window advisory request shape","requiredFields":list(PHASE2_FIELDS)},"outboundContract":{"endpoint":"/partner-api-contract/sample-response.json","description":"advisory-only response shape","fields":list(get_partner_sample_response_payload())},"openapiPreview":get_openapi_preview_payload(),"errorCatalog":ERRORS,"sampleRequest":get_partner_sample_request_payload(),"sampleResponse":get_partner_sample_response_payload(),"contractBoundaries":["static contract only","no real partner API enabled","no webhooks enabled","no autonomous actions","no real data"],"routeMap":{"integrationSandbox":"/integration-sandbox","integrationReadiness":"/integration-readiness","partnerApiContract":"/partner-api-contract","openapiPreview":"/partner-api-contract/openapi-preview.json","errors":"/partner-api-contract/errors.json","scenarioLibraryV4":"/scenario-library-v4","evaluationMatrixV2":"/evaluation-matrix-v2","demoFlow":"/demo-flow","productionGapAnalysis":"/production-gap-analysis"}}

def render_partner_api_contract_html()->str:
 p=get_partner_api_contract_payload(); errors="".join(f'<li><strong>{e["code"]}</strong>: {html.escape(e["meaning"])}</li>' for e in ERRORS)
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Partner API Contract v2</title><style>body{{font:16px system-ui;background:#07131b;color:#eef;padding:24px}}.badges{{display:flex;flex-wrap:wrap;gap:8px}}.badge,pre,.card{{border:1px solid #365;padding:10px;border-radius:12px}}pre{{white-space:pre-wrap;overflow:auto}}a{{color:#9ed}}</style></head><body><h1>Partner API Contract v2</h1><p>This is not a live partner API and not a real integration.</p><div class="badges"><span class="badge">Synthetic-only</span><span class="badge">Advisory-only</span><span class="badge">Static demo contract</span><span class="badge">No webhooks</span><span class="badge">No external calls</span><span class="badge">Deterministic rules authoritative</span></div><section class="card"><h2>Contract summary</h2><p>Inbound preview: POST {p["inboundContract"]["endpoint"]} — {p["inboundContract"]["description"]}.</p><p>Outbound preview: {p["outboundContract"]["endpoint"]} — {len(p["outboundContract"]["fields"])} advisory response fields.</p><a href="/partner-api-contract/openapi-preview.json">OpenAPI preview</a><h2>Sample request</h2><pre>{html.escape(json.dumps(p["sampleRequest"],indent=2))}</pre><h2>Sample response</h2><pre>{html.escape(json.dumps(p["sampleResponse"],indent=2))}</pre><h2>Error catalog</h2><ul>{errors}</ul></section></body></html>'''
