from __future__ import annotations
import html
from typing import Any
PHASE="Phase 27 - Route Reliability and Demo Resilience"
ROUTES=[("/command-center","core","none","static deterministic payload","critical"),("/expanded-benchmark","evidence","GPU/Jupyter","committed static artifact","critical"),("/fireworks-advisory","optional explanation","Fireworks","deterministic fallback","optional"),("/policy-sandbox","knowledge sandbox","none","static contract","supporting"),("/decision-simulator","review","none","static workflow","critical")]
def get_route_reliability_payload()->dict[str,Any]:
 rows=[{"route":r,"category":c,"expectedStatus":"available","optionalDependency":d,"fallbackBehavior":f,"demoCriticality":x} for r,c,d,f,x in ROUTES]
 return {"phase":PHASE,"status":"READY","syntheticOnly":True,"advisoryOnly":True,"runtimeGpuRequired":False,"runtimeExternalServiceRequired":False,"deterministicRulesAuthoritative":True,"autonomousActionsAllowed":False,"safeModeAvailable":True,"optionalDependencies":{"Fireworks":{"requiredForBoot":False,"fallback":"deterministic_fallback"},"GPU/Jupyter":{"requiredForBoot":False,"fallback":"static_artifact"},"External integrations":{"requiredForBoot":False,"fallback":"static_contract"}},"routeReliabilityRows":rows,"demoSafeMode":{"description":"Static evidence and deterministic routes remain available without optional enhancements.","routesStillAvailable":[r[0] for r in ROUTES],"routesWithOptionalEnhancement":["/fireworks-advisory"],"fallbackMessage":"Optional dependencies unavailable; deterministic static evidence remains available."},"routeMap":{"routeReliability":"/route-reliability","demoSafeMode":"/demo-safe-mode"}}
def render_route_reliability_html()->str:
 p=get_route_reliability_payload(); rows="".join(f'<tr><th>{html.escape(r["route"])}</th><td>{r["category"]}</td><td>{r["fallbackBehavior"]}</td></tr>' for r in p["routeReliabilityRows"])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Route Reliability</title><style>body{{font:16px system-ui;background:#07131b;color:#eef;padding:24px}}.card{{background:#102631;padding:16px;border-radius:12px}}table{{width:100%}}th,td{{padding:10px;text-align:left}}</style></head><body><h1>Route Reliability and Demo Resilience</h1><p>Static expected availability only; no self-HTTP monitoring.</p><section class="card"><h2>Demo safe mode</h2><p>{html.escape(p["demoSafeMode"]["fallbackMessage"])}</p></section><table><tbody>{rows}</tbody></table></body></html>'''
